Repository quintoandar/hive-metastore-client, pull requests merged in 2020-12, with the labels that each got.

#19 [DF-279] Add contributing.md, workflow.md and update readme.md
  CONTRIBUTING.md
  README.md
  WORKFLOW.md
  examples/README.md
Labels: documentation

#23 [DF-290] Add Pypi requirement for publish package
  .github/workflows/publish.yml
  requirements.dev.txt
Labels: enhancement

#20 [DF-300] Updating README
  README.md
Labels: documentation

#17 [DF-294] Adding PartitionBuilder Class
  docs/source/hive_metastore_client.builders.rst
  examples/add_partitions.py
  hive_metastore_client/builders/__init__.py
  hive_metastore_client/builders/partition_builder.py
  hive_metastore_client/hive_mestastore_client.py
  setup.cfg
  tests/unit/hive_metastore_client/builders/test_partition_builder.py
  tests/unit/hive_metastore_client/test_hive_mestastore_client.py
Labels: documentation, enhancement

#24 [DF-289] Update Docs
  docs/requirements.docs.txt
  docs/source/getstarted.md
  docs/source/index.rst
  docs/source/modules.rst
Labels: documentation

#25 [DF-281] Fix link to sonar badges
  README.md
Labels: documentation

#22 Release 1.0.0
  .github/workflows/publish.yml
  CHANGELOG.md
  setup.py
Labels: release

#26 [DF-304] Add docs about Builders and Thrift
  README.md
  docs/source/builders.md
  docs/source/getstarted.md
  docs/source/index.rst
  docs/source/thrift_instructions.md
  thrift_files/readme.md
Labels: documentation

#27 Update client import
  README.md
  docs/source/index.rst
  examples/README.md
  examples/add_columns_to_table.py
  examples/add_partitions.py
  examples/create_database.py
  examples/create_table.py
  hive_metastore_client/__init__.py
  tests/unit/hive_metastore_client/conftest.py
  tests/unit/hive_metastore_client/test_hive_mestastore_client.py
Labels: documentation, enhancement

#28 Adjusting docker image path
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: refactoring

#29 Update example imports and remove duplicated statement
  examples/create_table.py
Labels: documentation

#30 [DF-314] Adding method to drop columns from a table
  examples/drop_columns_from_table.py
  hive_metastore_client/hive_mestastore_client.py
  tests/unit/hive_metastore_client/test_hive_mestastore_client.py
Labels: documentation, enhancement

#33 [DF-316] Fix type in hive_metastore_client.py file name
  CONTRIBUTING.md
  Makefile
  docs/source/getstarted.md
  docs/source/hive_metastore_client.rst
  hive_metastore_client/__init__.py
  hive_metastore_client/hive_metastore_client.py
  tests/unit/hive_metastore_client/test_hive_metastore_client.py
Labels: bug

#34 Release 1.0.1
  CHANGELOG.md
  setup.py
Labels: release
