Repository quintoandar/hive-metastore-client, pull requests merged in 2021-02, with the labels that each got.

#43 [DAE-94] Add get_table_partition_keys and keys_names methods
  docs/source/getstarted.md
  examples/get_partition_keys_names.py
  examples/get_partition_keys_objects.py
  hive_metastore_client/hive_metastore_client.py
  tests/unit/hive_metastore_client/test_hive_metastore_client.py
Labels: documentation, enhancement

#44 [DAE-94] Release 1.0.4
  CHANGELOG.md
  setup.py
Labels: release

#46 [DAE-113] Adding base warning about changing thrift base files
  thrift_files/readme.md
Labels: documentation

#45 [DAE-113] Changing max_parts from get_partitions method to int32
  thrift_files/libraries/thrift_hive_metastore_client/ThriftHiveMetastore.py
  thrift_files/readme.md
  thrift_files/source/hive_metastore.thrift
Labels: enhancement

#48 Updating codeowners
  .github/CODEOWNERS
Labels: settings

#49 [DAE-116] Add method bulk drop
  docs/source/getstarted.md
  examples/bulk_drop_partitions.py
  hive_metastore_client/hive_metastore_client.py
  tests/unit/hive_metastore_client/test_hive_metastore_client.py
Labels: enhancement

#47 Adding bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#50 [DAE-121] Adding custom get_partition_values method
  docs/source/getstarted.md
  examples/get_partition_values_from_table.py
  hive_metastore_client/hive_metastore_client.py
  tests/unit/hive_metastore_client/test_hive_metastore_client.py
Labels: enhancement

#51 [DAE-122] Release 1.0.5
  CHANGELOG.md
  examples/drop_partition.py
  setup.py
Labels: release

#55 [DAE-126] Handle exception when table has no partitions
  hive_metastore_client/hive_metastore_client.py
  tests/unit/hive_metastore_client/test_hive_metastore_client.py
Labels: documentation, enhancement

#54 [DAE-125] Release 1.0.6
  CHANGELOG.md
  setup.py
Labels: release
