Repository quintoandar/hive-metastore-client, pull requests merged in 2021-03, with the labels that each got.

#56 [DAE-133] Removing types-comparison when dropping a column
  hive_metastore_client/hive_metastore_client.py
  tests/unit/hive_metastore_client/test_hive_metastore_client.py
Labels: bug

#57 [DAE-115] Add method add_partitions_to_table and deprecate add_partitions_if_not_exists
  docs/source/getstarted.md
  examples/add_partitions_if_not_exists.py
  examples/add_partitions_to_table.py
  hive_metastore_client/hive_metastore_client.py
  tests/unit/hive_metastore_client/test_hive_metastore_client.py
Labels: bug, documentation, enhancement

#58 [DAE-144] Release 1.0.7
  CHANGELOG.md
  setup.py
Labels: release
